//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMqtt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MqttServer {
            get {
                return ((string)(this["MqttServer"]));
            }
            set {
                this["MqttServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MqttUsername {
            get {
                return ((string)(this["MqttUsername"]));
            }
            set {
                this["MqttUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MqttPassword {
            get {
                return ((string)(this["MqttPassword"]));
            }
            set {
                this["MqttPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MqttTopic {
            get {
                return ((string)(this["MqttTopic"]));
            }
            set {
                this["MqttTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal MqttTimerInterval {
            get {
                return ((decimal)(this["MqttTimerInterval"]));
            }
            set {
                this["MqttTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkerScreenshotEnable {
            get {
                return ((bool)(this["WorkerScreenshotEnable"]));
            }
            set {
                this["WorkerScreenshotEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal WorkerScreenshotInterval {
            get {
                return ((decimal)(this["WorkerScreenshotInterval"]));
            }
            set {
                this["WorkerScreenshotInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SensorBatteryEnabled {
            get {
                return ((bool)(this["SensorBatteryEnabled"]));
            }
            set {
                this["SensorBatteryEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1883")]
        public decimal MqttPort {
            get {
                return ((decimal)(this["MqttPort"]));
            }
            set {
                this["MqttPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplicationMinimizeToTray {
            get {
                return ((bool)(this["ApplicationMinimizeToTray"]));
            }
            set {
                this["ApplicationMinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TTSSpeaker {
            get {
                return ((string)(this["TTSSpeaker"]));
            }
            set {
                this["TTSSpeaker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplicationRunAtStart {
            get {
                return ((bool)(this["ApplicationRunAtStart"]));
            }
            set {
                this["ApplicationRunAtStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SensorIsComputerUsedEnabled {
            get {
                return ((bool)(this["SensorIsComputerUsedEnabled"]));
            }
            set {
                this["SensorIsComputerUsedEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkerCameraEnabled {
            get {
                return ((bool)(this["WorkerCameraEnabled"]));
            }
            set {
                this["WorkerCameraEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkerCameraDevice {
            get {
                return ((string)(this["WorkerCameraDevice"]));
            }
            set {
                this["WorkerCameraDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTSEnabled {
            get {
                return ((bool)(this["TTSEnabled"]));
            }
            set {
                this["TTSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdSuspendEnabled {
            get {
                return ((bool)(this["CmdSuspendEnabled"]));
            }
            set {
                this["CmdSuspendEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdRebootEnabled {
            get {
                return ((bool)(this["CmdRebootEnabled"]));
            }
            set {
                this["CmdRebootEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdShutdownEnabled {
            get {
                return ((bool)(this["CmdShutdownEnabled"]));
            }
            set {
                this["CmdShutdownEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdHibernateEnabled {
            get {
                return ((bool)(this["CmdHibernateEnabled"]));
            }
            set {
                this["CmdHibernateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdToastEnabled {
            get {
                return ((bool)(this["CmdToastEnabled"]));
            }
            set {
                this["CmdToastEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdMonitorEnabled {
            get {
                return ((bool)(this["CmdMonitorEnabled"]));
            }
            set {
                this["CmdMonitorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CmdProcessEnabled {
            get {
                return ((bool)(this["CmdProcessEnabled"]));
            }
            set {
                this["CmdProcessEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MqttDiscoveryEnabled {
            get {
                return ((bool)(this["MqttDiscoveryEnabled"]));
            }
            set {
                this["MqttDiscoveryEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("homeassistant")]
        public string MqttDiscoveryPrefix {
            get {
                return ((string)(this["MqttDiscoveryPrefix"]));
            }
            set {
                this["MqttDiscoveryPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkerVolumeControlEnabled {
            get {
                return ((bool)(this["WorkerVolumeControlEnabled"]));
            }
            set {
                this["WorkerVolumeControlEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MqttDiscoveryFriendlyName {
            get {
                return ((string)(this["MqttDiscoveryFriendlyName"]));
            }
            set {
                this["MqttDiscoveryFriendlyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkerPerformanceInfoEnabled {
            get {
                return ((bool)(this["WorkerPerformanceInfoEnabled"]));
            }
            set {
                this["WorkerPerformanceInfoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal WorkerVolumeControlInterval {
            get {
                return ((decimal)(this["WorkerVolumeControlInterval"]));
            }
            set {
                this["WorkerVolumeControlInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal WorkerPerformanceInfoInterval {
            get {
                return ((decimal)(this["WorkerPerformanceInfoInterval"]));
            }
            set {
                this["WorkerPerformanceInfoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkerDiskInfoEnabled {
            get {
                return ((bool)(this["WorkerDiskInfoEnabled"]));
            }
            set {
                this["WorkerDiskInfoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal WorkerDiskInfoInterval {
            get {
                return ((decimal)(this["WorkerDiskInfoInterval"]));
            }
            set {
                this["WorkerDiskInfoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkerMediaPlayerEnabled {
            get {
                return ((bool)(this["WorkerMediaPlayerEnabled"]));
            }
            set {
                this["WorkerMediaPlayerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal WorkerCameraInterval {
            get {
                return ((decimal)(this["WorkerCameraInterval"]));
            }
            set {
                this["WorkerCameraInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkerScreenshotSaveLocation {
            get {
                return ((string)(this["WorkerScreenshotSaveLocation"]));
            }
            set {
                this["WorkerScreenshotSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkerCameraSaveLocation {
            get {
                return ((string)(this["WorkerCameraSaveLocation"]));
            }
            set {
                this["WorkerCameraSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkerVolumeControlDevice {
            get {
                return ((string)(this["WorkerVolumeControlDevice"]));
            }
            set {
                this["WorkerVolumeControlDevice"] = value;
            }
        }
    }
}
